FROM python:3.10-bullseye

RUN curl -sSL https://install.python-poetry.org | python3 -
RUN ln -s /root/.local/share/pypoetry/venv/bin/poetry /usr/local/bin/

COPY ./pyproject.toml ./poetry.lock ./code/

WORKDIR /code

RUN poetry config virtualenvs.create false
RUN poetry install --no-root --no-cache --no-interaction

RUN python -c "import nltk; nltk.download('punkt')"
RUN python -c "import nltk; nltk.download('averaged_perceptron_tagger')"

COPY ./ ./code

# add --proxy-headers when running behind proxy
CMD ["uvicorn", "web.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

# gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80
# uvicorn main:app --host 0.0.0.0 --port 80 --workers 4 --reload