# docker stack deploy ai-ml -c docker-compose.yml --prune
version: "3.8"

services:
  jupyter:
    image: "jupyter/datascience-notebook:notebook-6.5.2"
    volumes:
      - ./app:/home/jovyan/work
    ports:
      - 10000:8888

# build image first
  ai-ml:
    image: ai-ml-server
    ports:
      - 10001:80
    volumes:
      - ./app:/code/app