# docker stack deploy ai-ml -c docker-compose.yml --prune
version: "3.8"

services:
  jupyter:
    image: "jupyter/datascience-notebook:notebook-6.5.2"
    volumes:
      - ./:/home/jovyan/work
    ports:
      - 10000:8888

#  ai-ml:
#    image: ai-ml-server:latest
#    ports:
#      - 10001:80
#    volumes:
#    #  - ./app:/code/app
#      - ./:/code

  web:
    image: ai-ml-web:latest
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    ports:
      - 10002:80
    volumes:
      - ./:/code
      - ./data:/data/docs
      - ./db:/data/db