FROM python:3.10-bullseye

ARG POERTY_ARG

RUN curl -sSL https://install.python-poetry.org | python3 -
RUN ln -s /root/.local/share/pypoetry/venv/bin/poetry /usr/local/bin/

RUN apt-get update && apt-get install -y supervisor && rm -rf /var/lib/apt/lists/*
COPY ./docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY ./pyproject.toml ./poetry.lock ./code/

WORKDIR /code

RUN poetry config virtualenvs.create false
RUN poetry install --no-root --no-cache --no-interaction $POETRY_ARG

RUN python -c "import nltk; nltk.download('wordnet')"
RUN python -c "import nltk; nltk.download('punkt')"
RUN python -c "import nltk; nltk.download('averaged_perceptron_tagger')"

COPY ./ /code

# add --proxy-headers when running behind proxy
#CMD ["uvicorn", "web.main:app", "--host", "0.0.0.0", "--port", "80", "--reload", "--limit-concurrency", "10"]
CMD ["/usr/bin/supervisord"]

# gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80
# uvicorn main:app --host 0.0.0.0 --port 80 --workers 4 --reload